/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for opening a database. */
export interface JsOpenOptions {
  /** Enable automatic text embedding for semantic search. */
  autoEmbed?: boolean
  /** Open in read-only mode. */
  readOnly?: boolean
}
/** Download model files for auto-embedding. */
export declare function setup(): string
/**
 * StrataDB database handle.
 *
 * This is the main entry point for interacting with StrataDB from Node.js.
 * All data methods are async — they run on a blocking thread pool so the
 * Node.js event loop is never blocked.
 */
export declare class Strata {
  /** Open a database at the given path. */
  static open(path: string, options?: JsOpenOptions | undefined | null): Strata
  /** Create an in-memory database (no persistence). */
  static cache(): Strata
  /** Store a key-value pair. */
  kvPut(key: string, value: any): Promise<number>
  /**
   * Get a value by key. Optionally pass `asOf` (microseconds since epoch)
   * to read as of a past timestamp.
   */
  kvGet(key: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a key. */
  kvDelete(key: string): Promise<boolean>
  /** List keys with optional prefix filter. Optionally pass `asOf` for time-travel. */
  kvList(prefix?: string | undefined | null, asOf?: number | undefined | null): Promise<Array<string>>
  /** Get version history for a key. */
  kvHistory(key: string): Promise<any>
  /** Set a state cell value. */
  stateSet(cell: string, value: any): Promise<number>
  /** Get a state cell value. Optionally pass `asOf` for time-travel. */
  stateGet(cell: string, asOf?: number | undefined | null): Promise<any>
  /** Initialize a state cell if it doesn't exist. */
  stateInit(cell: string, value: any): Promise<number>
  /** Compare-and-swap update based on version. */
  stateCas(cell: string, newValue: any, expectedVersion?: number | undefined | null): Promise<number | null>
  /** Get version history for a state cell. */
  stateHistory(cell: string): Promise<any>
  /** Append an event to the log. */
  eventAppend(eventType: string, payload: any): Promise<number>
  /** Get an event by sequence number. Optionally pass `asOf` for time-travel. */
  eventGet(sequence: number, asOf?: number | undefined | null): Promise<any>
  /** List events by type. Optionally pass `asOf` for time-travel. */
  eventList(eventType: string, asOf?: number | undefined | null): Promise<any>
  /** Get total event count. */
  eventLen(): Promise<number>
  /** Set a value at a JSONPath. */
  jsonSet(key: string, path: string, value: any): Promise<number>
  /** Get a value at a JSONPath. Optionally pass `asOf` for time-travel. */
  jsonGet(key: string, path: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a JSON document. */
  jsonDelete(key: string, path: string): Promise<number>
  /** Get version history for a JSON document. */
  jsonHistory(key: string): Promise<any>
  /** List JSON document keys. Optionally pass `asOf` for time-travel. */
  jsonList(limit: number, prefix?: string | undefined | null, cursor?: string | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** Create a vector collection. */
  vectorCreateCollection(collection: string, dimension: number, metric?: string | undefined | null): Promise<number>
  /** Delete a vector collection. */
  vectorDeleteCollection(collection: string): Promise<boolean>
  /** List vector collections. */
  vectorListCollections(): Promise<any>
  /** Insert or update a vector. */
  vectorUpsert(collection: string, key: string, vector: Array<number>, metadata?: any | undefined | null): Promise<number>
  /** Get a vector by key. Optionally pass `asOf` for time-travel. */
  vectorGet(collection: string, key: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a vector. */
  vectorDelete(collection: string, key: string): Promise<boolean>
  /** Search for similar vectors. Optionally pass `asOf` for time-travel. */
  vectorSearch(collection: string, query: Array<number>, k: number, asOf?: number | undefined | null): Promise<any>
  /** Get statistics for a single collection. */
  vectorCollectionStats(collection: string): Promise<any>
  /** Batch insert/update multiple vectors. */
  vectorBatchUpsert(collection: string, vectors: Array<any>): Promise<Array<number>>
  /** Get the current branch name. */
  currentBranch(): Promise<string>
  /** Switch to a different branch. */
  setBranch(branch: string): Promise<void>
  /** Create a new empty branch. */
  createBranch(branch: string): Promise<void>
  /** Fork the current branch to a new branch, copying all data. */
  forkBranch(destination: string): Promise<any>
  /** List all branches. */
  listBranches(): Promise<Array<string>>
  /** Delete a branch. */
  deleteBranch(branch: string): Promise<void>
  /** Check if a branch exists. */
  branchExists(name: string): Promise<boolean>
  /** Get branch metadata with version info. */
  branchGet(name: string): Promise<any>
  /** Compare two branches. */
  diffBranches(branchA: string, branchB: string): Promise<any>
  /** Merge a branch into the current branch. */
  mergeBranches(source: string, strategy?: string | undefined | null): Promise<any>
  /** Get the current space name. */
  currentSpace(): Promise<string>
  /** Switch to a different space. */
  setSpace(space: string): Promise<void>
  /** List all spaces in the current branch. */
  listSpaces(): Promise<Array<string>>
  /** Delete a space and all its data. */
  deleteSpace(space: string): Promise<void>
  /** Force delete a space even if non-empty. */
  deleteSpaceForce(space: string): Promise<void>
  /** Check database connectivity. */
  ping(): Promise<string>
  /** Get database info. */
  info(): Promise<any>
  /** Flush writes to disk. */
  flush(): Promise<void>
  /** Trigger compaction. */
  compact(): Promise<void>
  /** Export a branch to a bundle file. */
  branchExport(branch: string, path: string): Promise<any>
  /** Import a branch from a bundle file. */
  branchImport(path: string): Promise<any>
  /** Validate a bundle file without importing. */
  branchValidateBundle(path: string): Promise<any>
  /** Begin a new transaction. */
  begin(readOnly?: boolean | undefined | null): Promise<void>
  /** Commit the current transaction. */
  commit(): Promise<number>
  /** Rollback the current transaction. */
  rollback(): Promise<void>
  /** Get current transaction info. */
  txnInfo(): Promise<any>
  /** Check if a transaction is currently active. */
  txnIsActive(): Promise<boolean>
  /** Delete a state cell. */
  stateDelete(cell: string): Promise<boolean>
  /** List state cell names with optional prefix filter. Optionally pass `asOf` for time-travel. */
  stateList(prefix?: string | undefined | null, asOf?: number | undefined | null): Promise<Array<string>>
  /** Get a value by key with version info. */
  kvGetVersioned(key: string): Promise<any>
  /** Get a state cell value with version info. */
  stateGetVersioned(cell: string): Promise<any>
  /** Get a JSON document value with version info. */
  jsonGetVersioned(key: string): Promise<any>
  /** List keys with pagination support. Optionally pass `asOf` for time-travel. */
  kvListPaginated(prefix?: string | undefined | null, limit?: number | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** List events by type with pagination support. Optionally pass `asOf` for time-travel. */
  eventListPaginated(eventType: string, limit?: number | undefined | null, after?: number | undefined | null, asOf?: number | undefined | null): Promise<any>
  /**
   * Search for similar vectors with optional filter and metric override.
   * Optionally pass `asOf` for time-travel.
   */
  vectorSearchFiltered(collection: string, query: Array<number>, k: number, metric?: string | undefined | null, filter?: Array<any> | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** Create a new space explicitly. */
  spaceCreate(space: string): Promise<void>
  /** Check if a space exists in the current branch. */
  spaceExists(space: string): Promise<boolean>
  /** Search across multiple primitives for matching content. */
  search(query: string, k?: number | undefined | null, primitives?: Array<string> | undefined | null): Promise<any>
  /** Apply retention policy to trigger garbage collection. */
  retentionApply(): Promise<void>
  /**
   * Close the database, releasing all resources.
   *
   * After calling `close()`, any further method call on this instance will
   * fail with a "Lock poisoned" or similar error.  This mirrors the
   * `client.close()` pattern used by every major Node.js database driver.
   */
  close(): Promise<void>
  /** Get the time range (oldest and latest timestamps) for the current branch. */
  timeRange(): Promise<any>
}
